#! /bin/sh

test -d /mnt/site/htdocs || { mkdir /mnt/site/htdocs ; chown ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} /mnt/site/htdocs ; }
test -f /mnt/site/htdocs/index.mhtml || { cp index-default.mhtml /mnt/site/htdocs/index.mhtml ; chown ${APACHE_RUN_USER}:${APACHE_RUN_GROUP} /mnt/site/htdocs/index.mhtml ; }

chown www-data:www-data -R /mnt/site

/usr/sbin/apache2 -D FOREGROUND
