name: docker-test-and-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  call-workflow-in-another-repo:
    uses: DSK-Docker/workflows/.github/workflows/main.yml@master
